name: CypressTests_z_DOCKEREMczerwiec # nazwa pipeline'u (widoczna w GitHub Actions)

on:
  push:
    branches:
      - main # uruchamia się tylko na push do main (np. po merge PR)
  pull_request: # uruchamia się na każdy pull request
  workflow_dispatch: # ręczne uruchomienie

jobs:
  cypress:
    runs-on: ubuntu-latest # GitHub tworzy świeży Linux (runner)

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6 # pobiera Twój kod z repozytorium (Dockerfile, testy, config)

      - name: Build Docker image
        run: docker build -t cypress-test . # buduje obraz z Twojego Dockerfile
        # (tu dzieje się npm install + cypress install)

      - name: Run Cypress tests in Docker
        run: docker run --rm cypress-test # uruchamia kontener i testy Cypress
        # --rm = usuń kontener po zakończeniu
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # przekazuje secret czyli token dla bezpieczeństwa
