name: CypressTests1
on: [push, workflow_dispatch]

jobs:
  cypress:
    run-on: ubuntu-latest # uruchamia na najnowszym ubuntu uwaga w chmurze !!! nie musisz go miec

    steps:
      - uses: actions/checkout@v4 # krok 1 zrob checkout z repo z ktorego bierzesz kod 
      - uses: actions/setup-node@v4 # krok 2 zainstaluj srodowisko nodejs
        with:
          node-version: 24 # sami okreslamy
          cache: npm

      - run: npm ci # uruchom skrypty npm w srodowisku ciaglej integracji 
      - run: npx cypress run
      # run: npm run mytests


